from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.ui import Select
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as wait
from decouple import config
import logging
import time
import pyautogui

logging.basicConfig(level=logging.DEBUG,
                    filename="postudio.log", 
                    format='%(asctime)s %(name)-12s %(levelname)-8s %(message)s',
                    datefmt='%m-%d %H:%M',
                    filemode='a+') 
console = logging.StreamHandler()
console.setLevel(logging.INFO)
#console.setLevel(logging.DEBUG)
formatter = logging.Formatter(fmt='%(asctime)s %(levelname)-8s %(message)s',datefmt='%Y-%m-%d %H:%M:%S')
console.setFormatter(formatter)
logging.getLogger('').addHandler(console)
logger_login= logging.getLogger('login.py')
logger_logout= logging.getLogger('logout.py')



def signin():
	try:
		URL_PATH = config('URL')
		driver= webdriver.Chrome()
		driver.implicitly_wait(5)
		driver.set_window_size(1524, 1024)
		#driver.maximize_window()
		actions = ActionChains(driver)
		driver.get(URL_PATH)
		logger_login.info("Connection created successfully")
		time.sleep(1)
		username = driver.find_element_by_xpath('//*[@id="email"]')
		username.clear()
		username.send_keys(config('username'))
		password = driver.find_element_by_xpath('//*[@id="password"]')
		password.clear()
		password.send_keys(config('password'))
		login= driver.find_element_by_xpath('//*[@id="root"]/div[2]/div/div/form/div[3]/button')
		login.click()
		time.sleep(2)
		logger_login.info("login successfully")
		time.sleep(2)

		''' create storyboard '''
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div/div/div/div[1]/div/div[1]/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Create Storyboard']"))).click()
		create_storyboard = driver.find_element_by_xpath('//*[@id="createStoryboard"]')
		create_storyboard.clear()
		create_storyboard.send_keys(config('STORYBOARD_NAME'))
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div/div/div/div[1]/div/div[2]/div[2]/button').click()
		time.sleep(2)
		logger_login.info("storyborad created successfully")
		
		'''back button'''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[2]/div/div[1]/button').click()
		time.sleep(3)
		

		''' open storyboard '''
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div/div/div/div[2]/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Permission Test']"))).click()
		logger_login.info("storyborad opened successfully")
		time.sleep(3)

		''' browse assets and folders'''
		# first image upload
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Browse Assets']"))).click()
		pyautogui.moveTo(250, 240)
		time.sleep(4)
		pyautogui.click(250, 240)
		time.sleep(1)
		logger_login.info("pictures folder seleted")
		pyautogui.moveTo(500, 160)
		pyautogui.click(500, 160)
		logger_login.info("first image selected")
		pyautogui.moveTo(1250, 50)
		pyautogui.click(1250, 50)
		logger_login.info("first image opened")
		time.sleep(2)
		# second image upload
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		pyautogui.moveTo(250, 240)
		pyautogui.click(250, 240)
		time.sleep(1)
		logger_login.info("pictures folder seleted")
		pyautogui.moveTo(500, 260)
		pyautogui.click(500, 260)
		logger_login.info("second image selected")
		pyautogui.moveTo(1250, 50)
		pyautogui.click(1250, 50)
		logger_login.info("second image opened")
		time.sleep(2)
		## one video upload
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		#pyautogui.moveTo(250, 300, duration = 1)
		#pyautogui.click(250, 300)
		#time.sleep(2)
		#logger_login.info("pictures folder seleted:",pyautogui.position())
		#pyautogui.moveTo(500, 210, duration = 1)
		#pyautogui.click(500, 210)
		#logger_login.info("one video selected:",pyautogui.position())
		#pyautogui.moveTo(1250, 50, duration = 1)
		#pyautogui.click(1250, 50)
		#logger_login.info("one video opened:",pyautogui.position())
		#pyautogui.moveTo(100, 50, duration = 1)
		#pyautogui.click(100, 50)
		#logger_login.info("one video close button clicked:",pyautogui.position())
		#time.sleep(4)

		''' add storyboard brief '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Add Storyboard Brief']"))).click()
		time.sleep(1)
		storyboard_brief = driver.find_element_by_xpath('//*[@id="brief"]')
		storyboard_brief.clear()
		storyboard_brief.send_keys(config('storyboard_brief'))
		storyboard_update= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		storyboard_update.click()
		time.sleep(1)

		''' add collaborator '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		time.sleep(3)
		add_collaborator = driver.find_element_by_xpath('//*[@id="users"]')
		add_collaborator.clear()
		add_collaborator.send_keys(config('permission_collab_email'))
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[1]/div/div/div/div/button')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		#time.sleep(4)
		pyautogui.moveTo(1200, 380)
		pyautogui.click(1200, 380)
		#logger_login.info("first collaborator selected")
		time.sleep(2)
		collaborator_update=driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		collaborator_update.click()
		time.sleep(4)

		''' create task '''
		driver.maximize_window()
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Create & Assign Tasks to your team']"))).click()
		time.sleep(3)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[1]/div/div/div').click()
		driver.find_element_by_xpath('//*[@id="menu-"]/div[3]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//li[text()='Video Editing']"))).click()
		time.sleep(1)
		assign_to = driver.find_element_by_xpath('//*[@id="assignTo"]')
		assign_to.clear()
		assign_to.send_keys(config('permission_assign_task'))
		time.sleep(2)
		pyautogui.moveTo(1175, 425)
		pyautogui.click(1175, 425)
		logger_login.info("assign task user selected")
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[3]/div/div/div/button').click()
		time.sleep(2)
		pyautogui.moveTo(1175, 450)
		pyautogui.click(1175, 450)
		logger_login.info("date next button clicked.")
		time.sleep(1)
		pyautogui.moveTo(1195, 600)
		pyautogui.click(1195, 600)
		logger_login.info("date selected")
		time.sleep(1)
		description = driver.find_element_by_xpath('//*[@id="description"]')
		description.clear()
		description.send_keys(config('task_description'))
		time.sleep(2)
		create_task = driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		create_task.click()
		time.sleep(4)

		''' disable permission to team member '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		pyautogui.moveTo(1255, 480,duration=1)
		pyautogui.click(1255, 480)
		time.sleep(1)
		logger_login.info("setting button clicked")
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]/span/span[1]/input').click()	
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]/span/span[1]/input').click()	
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]/span/span[1]/input').click()
		time.sleep(1)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Update']"))).click()
		time.sleep(3)

		''' disable permission to collaborator '''
		pyautogui.moveTo(1258, 580)
		pyautogui.click(1258, 580)
		time.sleep(2)
		logger_login.info("setting button clicked")
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]/span/span[1]/input').click()		
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[6]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[6]/span/span[1]/input').click()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Update']"))).click()
		time.sleep(7)
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("collaboarator close button clicked")
		time.sleep(3)

		''' logout view '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div/div/button/span[1]/div').click()
		asset_over= driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li')
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Sign Out']"))).click()
		time.sleep(2)
		logger_login.info('logout successfully')

		''' login for team member and collaborator permission verify '''
		username = driver.find_element_by_xpath('//*[@id="email"]')
		username.clear()
		username.send_keys(config('approved_username'))
		password = driver.find_element_by_xpath('//*[@id="password"]')
		password.clear()
		password.send_keys(config('approved_password'))
		login= driver.find_element_by_xpath('//*[@id="root"]/div[2]/div/div/form/div[3]/button')
		login.click()
		logger_login.info("user login for verification successfully")
		driver.maximize_window()
		time.sleep(4)
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]')
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]/div[1]/div/div[1]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Permission Test']"))).click()
		time.sleep(2)
		''' storyboard brief verifation'''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[1]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Storyboard Brief']"))).click()
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("storyboard brief close button clicked")
		''' image permissions check '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[1]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]/div/button').click()
		time.sleep(3)
		logger_login.info("asset permission like approve,review,share are verify")
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("click mouse anywhere")
		time.sleep(1)
		''' task details verification'''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Task Details']"))).click()
		logger_login.info("task details button clicked")
		time.sleep(2)
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[2]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Complete']"))).click()
		logger_login.info("task completed button clicked")
		time.sleep(3)
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("task details close button clicked")
		time.sleep(3)
		# image upload verification
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		#pyautogui.moveTo(250, 240)
		#pyautogui.click(250, 240)
		#time.sleep(1)
		#logger_login.info("pictures folder seleted")
		#pyautogui.moveTo(500, 260)
		#pyautogui.click(500, 260)
		#logger_login.info("second image selected")
		#pyautogui.moveTo(1250, 50)
		#pyautogui.click(1250, 50)
		#logger_login.info("second image opened")
		#time.sleep(2)
		''' back button '''
		pyautogui.moveTo(45,176)
		pyautogui.click(45,176)
		print(pyautogui.position())
		time.sleep(3)
			
		''' collaborated storyboard tab clicked'''
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tab-1"]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Collaborated Storyboards']"))).click()
		time.sleep(2)
		''' storyboard selected '''
		pyautogui.moveTo(55,666,duration=2)
		pyautogui.click(55,666)
		print(pyautogui.position())
		logger_login.info("collaborated storyboard selected")
		time.sleep(3)
		''' add storyboard brief '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Brief']"))).click()
		storyboard_brief = driver.find_element_by_xpath('//*[@id="brief"]')
		storyboard_brief.clear()
		storyboard_brief.send_keys('hello.')
		storyboard_update= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		storyboard_update.click()
		time.sleep(2)

		''' create task '''
		driver.maximize_window()
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Create & Assign Tasks to your team']"))).click()
		time.sleep(3)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[1]/div/div/div').click()
		driver.find_element_by_xpath('//*[@id="menu-"]/div[3]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//li[text()='Video Editing']"))).click()
		time.sleep(1)
		assign_to = driver.find_element_by_xpath('//*[@id="assignTo"]')
		assign_to.clear()
		assign_to.send_keys(config('permission_assign_task_user'))
		time.sleep(2)
		pyautogui.moveTo(1175, 425)
		pyautogui.click(1175, 425)
		logger_login.info("assign task user selected")
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[3]/div/div/div/button').click()
		time.sleep(2)
		pyautogui.moveTo(1175, 450)
		pyautogui.click(1175, 450)
		logger_login.info("date next button clicked.")
		time.sleep(1)
		pyautogui.moveTo(1195, 600)
		pyautogui.click(1195, 600)
		logger_login.info("date selected")
		time.sleep(1)
		description = driver.find_element_by_xpath('//*[@id="description"]')
		description.clear()
		description.send_keys(config('task_description'))
		time.sleep(2)
		create_task = driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		create_task.click()
		time.sleep(7)
		pyautogui.moveTo(1290, 230)
		pyautogui.click(1290, 230)
		logger_login.info("task close button clicked")

		''' add collaborator '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		time.sleep(3)
		pyautogui.moveTo(1290, 230)
		pyautogui.click(1290, 230)
		logger_login.info("collaboarator close button clicked")
		time.sleep(6)
		
		''' image upload verification ''' 
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		pyautogui.moveTo(250, 240)
		pyautogui.click(250, 240)
		time.sleep(1)
		logger_login.info("pictures folder seleted")
		pyautogui.moveTo(500, 260)
		pyautogui.click(500, 260)
		logger_login.info("second image selected")
		pyautogui.moveTo(1250, 50)
		pyautogui.click(1250, 50)
		logger_login.info("second image opened")
		time.sleep(4)
		''' image permissions check '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[1]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]/div/button').click()
		time.sleep(3)
		logger_login.info("asset permission like approve,review,share are verify")
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("click mouse anywhere")
		time.sleep(1)
		
		''' logout view '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div/div/button/span[1]/div').click()
		asset_over= driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li')
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Sign Out']"))).click()
		time.sleep(2)
		logger_login.info('logout successfully')

		''' again login user 1 '''
		username = driver.find_element_by_xpath('//*[@id="email"]')
		username.clear()
		username.send_keys(config('username'))
		password = driver.find_element_by_xpath('//*[@id="password"]')
		password.clear()
		password.send_keys(config('password'))
		login= driver.find_element_by_xpath('//*[@id="root"]/div[2]/div/div/form/div[3]/button')
		login.click()
		time.sleep(2)
		logger_login.info("again user 1 login successfully")
		time.sleep(2)

		''' open storyboard '''
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div/div/div/div[2]/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Permission Test']"))).click()
		logger_login.info("storyborad opened successfully")
		driver.set_window_size(1524, 1024)
		time.sleep(3)

		''' assign permission to team member '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		pyautogui.moveTo(1255, 480,duration=1)
		pyautogui.click(1255, 480)
		time.sleep(1)
		logger_login.info("setting button clicked")
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]/span/span[1]/input').click()	
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]/span/span[1]/input').click()	
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]/span/span[1]/input').click()
		time.sleep(1)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Update']"))).click()
		time.sleep(3)

		''' assign permission to collaborator '''
		pyautogui.moveTo(1258, 580)
		pyautogui.click(1258, 580)
		time.sleep(2)
		logger_login.info("setting button clicked")
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[1]/span/span[1]/input').click()		
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[2]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[3]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[4]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[5]/span/span[1]/input').click()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[6]')
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[2]/div[6]/span/span[1]/input').click()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Update']"))).click()
		time.sleep(7)
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("collaboarator close button clicked")
		time.sleep(3)

		''' logout view '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div/div/button/span[1]/div').click()
		asset_over= driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li')
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Sign Out']"))).click()
		time.sleep(2)
		logger_login.info('logout successfully')

		''' login for team member and collaborator permission verify '''
		username = driver.find_element_by_xpath('//*[@id="email"]')
		username.clear()
		username.send_keys(config('approved_username'))
		password = driver.find_element_by_xpath('//*[@id="password"]')
		password.clear()
		password.send_keys(config('approved_password'))
		login= driver.find_element_by_xpath('//*[@id="root"]/div[2]/div/div/form/div[3]/button')
		login.click()
		logger_login.info("user login for verification successfully")
		driver.maximize_window()
		time.sleep(4)
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]')
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]/div[1]')
		driver.find_element_by_xpath('//*[@id="task_tabs-tabpanel-0"]/div/div/div/div/div/div[2]/div[1]/div/div[1]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Permission Test']"))).click()
		time.sleep(2)
		''' storyboard brief verifation'''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[1]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Storyboard Brief']"))).click()
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("storyboard brief close button clicked")
		''' image permissions check '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[1]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]/div/button').click()
		time.sleep(3)
		logger_login.info("asset permission like approve,review,share are verify")
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("click mouse anywhere")
		time.sleep(1)
		''' task details verification '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div/div/div[2]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Task Details']"))).click()
		logger_login.info("task details button clicked")
		time.sleep(2)
		asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[2]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Complete']"))).click()
		logger_login.info("task completed button clicked")
		time.sleep(3)
		pyautogui.moveTo(1290, 230,duration=1)
		pyautogui.click(1290, 230)
		logger_login.info("task details close button clicked")
		time.sleep(3)
		# image upload verification
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		#pyautogui.moveTo(250, 240)
		#pyautogui.click(250, 240)
		#time.sleep(1)
		#logger_login.info("pictures folder seleted")
		#pyautogui.moveTo(500, 260)
		#pyautogui.click(500, 260)
		#logger_login.info("second image selected")
		#pyautogui.moveTo(1250, 50)
		#pyautogui.click(1250, 50)
		#logger_login.info("second image opened")
		#time.sleep(2)
		''' back button '''
		#pyautogui.moveTo(45,176)
		#pyautogui.click(45,176)
		#print(pyautogui.position())
		#time.sleep(3)
		#''' collaborated storyboard tab clicked'''
		#driver.find_element_by_xpath('//*[@id="storyboard_tabs-tab-1"]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Collaborated Storyboards']"))).click()
		#time.sleep(2)
		#''' storyboard selected '''
		#pyautogui.moveTo(55,666,duration=2)
		#pyautogui.click(55,666)
		#print(pyautogui.position())
		#logger_login.info("collaborated storyboard selected")
		#time.sleep(3)
		#''' add storyboard brief '''
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[1]/div/div[2]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//h3[text()='Brief']"))).click()
		#storyboard_brief = driver.find_element_by_xpath('//*[@id="brief"]')
		#storyboard_brief.clear()
		#storyboard_brief.send_keys('hello.')
		#storyboard_update= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		#storyboard_update.click()
		#time.sleep(2)

		''' create task '''
		driver.maximize_window()
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[2]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Create & Assign Tasks to your team']"))).click()
		#time.sleep(3)
		#driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[1]/div/div/div').click()
		#driver.find_element_by_xpath('//*[@id="menu-"]/div[3]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//li[text()='Video Editing']"))).click()
		#time.sleep(1)
		#assign_to = driver.find_element_by_xpath('//*[@id="assignTo"]')
		#assign_to.clear()
		#assign_to.send_keys(config('permission_assign_task_user'))
		#time.sleep(2)
		#pyautogui.moveTo(1175, 425)
		#pyautogui.click(1175, 425)
		#logger_login.info("assign task user selected")
		#time.sleep(2)
		#driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[3]/div/div/div/button').click()
		#time.sleep(2)
		#pyautogui.moveTo(1175, 450)
		#pyautogui.click(1175, 450)
		#logger_login.info("date next button clicked.")
		#time.sleep(1)
		#pyautogui.moveTo(1195, 600)
		#pyautogui.click(1195, 600)
		#logger_login.info("date selected")
		#time.sleep(1)
		#description = driver.find_element_by_xpath('//*[@id="description"]')
		#description.clear()
		#description.send_keys(config('task_description'))
		#time.sleep(2)
		#create_task = driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		#create_task.click()
		#time.sleep(4)

		''' add collaborator '''
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		#time.sleep(3)
		#add_collaborator = driver.find_element_by_xpath('//*[@id="users"]')
		#add_collaborator.clear()
		#add_collaborator.send_keys(config('permission_collaborator_email'))
		#asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[1]/div/div/div/div/button')
		#hover = ActionChains(driver).move_to_element(asset_over)
		#hover.perform()
		##time.sleep(4)
		#pyautogui.moveTo(1200, 380)
		#pyautogui.click(1200, 380)
		##logger_login.info("first collaborator selected")
		#time.sleep(2)
		#collaborator_update=driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		#collaborator_update.click()
		#time.sleep(4)
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		#pyautogui.moveTo(1280, 700,duration=3)
		##pyautogui.click(1280, 500)
		##logger_login.info("hover mouse for delete collaborator")
		##driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[3]/div[2]/div[2]/button').click()
		##time.sleep(2)
		##driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div[3]/div[2]/div[2]/button').click()
		##time.sleep(7)
		#pyautogui.moveTo(1290, 230)
		#pyautogui.click(1290, 230)
		#logger_login.info("collaboarator close button clicked")
		#time.sleep(6)
		
		''' image upload verification ''' 
		##driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		##driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[1]')
		##wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Upload Assets']"))).click()
		##pyautogui.moveTo(250, 240)
		##pyautogui.click(250, 240)
		##time.sleep(1)
		##logger_login.info("pictures folder seleted")
		##pyautogui.moveTo(500, 260)
		##pyautogui.click(500, 260)
		##logger_login.info("second image selected")
		##pyautogui.moveTo(1250, 50)
		##pyautogui.click(1250, 50)
		##logger_login.info("second image opened")
		#''' image permissions check '''
		##driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]')
		##asset_over= driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[1]')
		##hover = ActionChains(driver).move_to_element(asset_over)
		##hover.perform()
		##time.sleep(2)
		##driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]')
		##driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[4]/div[1]/div[3]/div[2]/div/button').click()
		##time.sleep(3)
		##logger_login.info("asset permission like approve,review,share are verify")
		##pyautogui.moveTo(1290, 230,duration=1)
		##pyautogui.click(1290, 230)
		##logger_login.info("click mouse anywhere")
		##time.sleep(1)
		
		''' logout view '''
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		#driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div/div/button/span[1]/div').click()
		#asset_over= driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		#hover = ActionChains(driver).move_to_element(asset_over)
		#hover.perform()
		#driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li')
		#driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li/div')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Sign Out']"))).click()
		#time.sleep(2)
		#logger_login.info('logout successfully')

		''' login user 1 for delete task,delete collaborator and deleted storyboard '''
		username = driver.find_element_by_xpath('//*[@id="email"]')
		username.clear()
		username.send_keys(config('username'))
		password = driver.find_element_by_xpath('//*[@id="password"]')
		password.clear()
		password.send_keys(config('password'))
		login= driver.find_element_by_xpath('//*[@id="root"]/div[2]/div/div/form/div[3]/button')
		login.click()
		time.sleep(2)
		logger_login.info("user 1 login for delete task,collaborator and storybord successfully")
		time.sleep(2)

		''' open storyboard '''
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="storyboard_tabs-tabpanel-0"]/div/div/div/div[2]/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Permission Test']"))).click()
		logger_login.info("storyborad opened successfully")
		driver.set_window_size(1524, 1024)
		time.sleep(3)

		''' task details for delete task '''
		#taskdetails_sidemenu = driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/button')
		#taskdetails_sidemenu.click()
		#time.sleep(3)
		#driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li[3]')
		#driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li[3]/div')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Task Details']"))).click()
		#time.sleep(3)
		#driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[2]/div').click()
		#driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Update']"))).click()
		#driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[1]')
		#wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//span[text()='Delete']"))).click()
		#time.sleep(4)
		#pyautogui.moveTo(820, 501)
		#time.sleep(2)
		#pyautogui.click(820, 501)
		#logger_login.info("task deleted.")		
		#time.sleep(4)

		''' remove collaborators and team members '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[1]')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[3]/div[3]/div/div[2]')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Add users to collaborate on this Storyboard']"))).click()
		pyautogui.moveTo(1294, 487,duration=1)
		pyautogui.click(1294, 487)
		time.sleep(1)
		pyautogui.moveTo(1294, 487,duration=1)
		pyautogui.click(1294, 487)
		time.sleep(1)
		pyautogui.moveTo(1294, 487,duration=1)
		pyautogui.click(1294, 487)
		time.sleep(7)
		pyautogui.moveTo(1290, 230)
		pyautogui.click(1290, 230)
		logger_login.info("collaboarator close button clicked")
		time.sleep(3)

		''' delete storyboard '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[2]/div/div[2]/div/div[2]/div[2]/div/button').click()
		time.sleep(2)
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li[5]/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Manage Storyboard']"))).click()
		time.sleep(1)
		driver.find_element_by_xpath('//*[@id="root"]/div[3]/div/div/div[3]/button[1]').click()
		time.sleep(1)
		pyautogui.moveTo(820, 501)
		pyautogui.click(820, 501)
		logger_login.info("storyboard deleted.")		
		time.sleep(4)
		time.sleep(2)
		
		''' logout view '''
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div')
		driver.find_element_by_xpath('//*[@id="root"]/div[1]/div/div[1]/header/div/div/div/button/span[1]/div').click()
		asset_over= driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]')
		hover = ActionChains(driver).move_to_element(asset_over)
		hover.perform()
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li')
		driver.find_element_by_xpath('//*[@id="customized-menu"]/div[3]/ul/li/div')
		wait(driver, 1).until(EC.element_to_be_clickable((By.XPATH, "//p[text()='Sign Out']"))).click()
		time.sleep(2)
		logger_login.info('logout successfully')
			

		''' close browser '''
		driver.close()
		driver.quit()
	except Exception as e:
		logger_login.debug("Failed to connect internet: %s" %e)
		print("Failed to connect internet: %s" %e)
		driver.close()
		driver.quit()

if __name__ == '__main__':
    signin()